# Generated by Django 4.2.29 on 2026-04-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('expedie', 'Expédié'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('entrepot_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='logistique.entrepot')),
                ('entrepot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='logistique.entrepot')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.transfertstock')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='logistique.entrepot')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'unique_together': {('entrepot', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockParEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='logistique.emplacement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_emplacements', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Stock par emplacement',
                'verbose_name_plural': 'Stocks par emplacement',
                'unique_together': {('produit', 'emplacement')},
            },
        ),
    ]
