# Generated by Django 4.2.29 on 2026-05-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_employe_avatar_type_employe_photo'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepot',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe'),
        ),
    ]
