# Generated by Django 4.2.29 on 2026-05-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0002_employe_avatar_type_employe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('nb_etages', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
            },
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etage', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='batiments.batiment')),
            ],
            options={
                'verbose_name': 'Étage',
                'verbose_name_plural': 'Étages',
                'unique_together': {('batiment', 'numero_etage')},
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_local', models.CharField(choices=[('bureau', 'Bureau'), ('salle_reunion', 'Salle de réunion'), ('depot', 'Dépôt / Stockage'), ('labo', 'Laboratoire'), ('autre', 'Autre')], default='bureau', max_length=30)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='en m²', max_digits=6)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='batiments.etage')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
            },
        ),
    ]
