# Generated by Django 4.2.29 on 2026-05-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='avatar_type',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employes/'),
        ),
    ]
