# Generated by Django 4.2.29 on 2026-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Maroc', max_length=100)),
                ('ice', models.CharField(blank=True, max_length=20, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('delai_livraison', models.IntegerField(default=7, help_text='Jours')),
                ('conditions_paiement', models.CharField(blank=True, default='30 jours', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
    ]
