# Generated by Django 4.2.29 on 2026-05-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents_fournisseurs/')),
                ('nom', models.CharField(max_length=255)),
                ('taille', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
