# Generated by Django 4.2.29 on 2026-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_documentfournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fournisseurs/'),
        ),
    ]
